baseurl = "https://budiariyanto.github.io/"
title = "Budi Ariyanto"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Budi Ariyanto"
disqusShortname = "budiariyanto"
googleAnalytics = "UA-57148145-1"

[Author]
    name = "Budi Ariyanto"
    profile = "https://google.com/+BudiAriyanto"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    headline = "My Personal Blog"
    description = "About My Actvities"
    github = "https://github.com/budiariyanto"
    linkedin = "https://linkedin.com/in/budiariyanto/"
    gplus = "https://google.com/+BudiAriyanto"
    twitter = "https://twitter.com/fxbudiariyanto"
    #stackoverflow = "http://stackoverflow.com/users/XXX/YYY"
    email = "fx.budi.ariyanto@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, January 2, 2006"
    #highlightJsUrl = ""
    highlightJsLocalUrl = "js/highlight.min.js"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Quotes"
    url = "/quote/"
    weight = 2

#[[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 2

#[[menu.main]]
#    name = "Contact"
#    url = "/page/contact/"
#    weight = 3

#[[menu.main]]
#    name = "About"
#    url = "/page/about/"
#    weight = 4
